version: '3.8'
services:
  # 1. RabbitMQ (Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_distribuidas
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ecommerce-net

  # 2. Base de Datos (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Carga script inicial
    networks:
      - ecommerce-net

  # 3. Order Service
  order-service:
    build: ../order-service
    container_name: order_service
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://admin:adminpassword@postgres:5432/ecommerce_db
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - ecommerce-net

  # 4. Inventory Service
  inventory-service:
    build: ../inventory-service
    container_name: inventory_service
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://admin:adminpassword@postgres:5432/ecommerce_db
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge